/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as CompetitionsIndexImport } from './routes/competitions/index'
import { Route as CompetitionsIdImport } from './routes/competitions/$id'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CompetitionsIndexRoute = CompetitionsIndexImport.update({
  id: '/competitions/',
  path: '/competitions/',
  getParentRoute: () => rootRoute,
} as any)

const CompetitionsIdRoute = CompetitionsIdImport.update({
  id: '/competitions/$id',
  path: '/competitions/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/competitions/$id': {
      id: '/competitions/$id'
      path: '/competitions/$id'
      fullPath: '/competitions/$id'
      preLoaderRoute: typeof CompetitionsIdImport
      parentRoute: typeof rootRoute
    }
    '/competitions/': {
      id: '/competitions/'
      path: '/competitions'
      fullPath: '/competitions'
      preLoaderRoute: typeof CompetitionsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/competitions/$id': typeof CompetitionsIdRoute
  '/competitions': typeof CompetitionsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/competitions/$id': typeof CompetitionsIdRoute
  '/competitions': typeof CompetitionsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/competitions/$id': typeof CompetitionsIdRoute
  '/competitions/': typeof CompetitionsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/competitions/$id' | '/competitions'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/competitions/$id' | '/competitions'
  id: '__root__' | '/' | '/competitions/$id' | '/competitions/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompetitionsIdRoute: typeof CompetitionsIdRoute
  CompetitionsIndexRoute: typeof CompetitionsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompetitionsIdRoute: CompetitionsIdRoute,
  CompetitionsIndexRoute: CompetitionsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/competitions/$id",
        "/competitions/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/competitions/$id": {
      "filePath": "competitions/$id.tsx"
    },
    "/competitions/": {
      "filePath": "competitions/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
